---
title: "Data Visuals and Analysis"
---

## [#Tidy Tuesday](https://github.com/rbolt13/tidytuesday)

TidyTuesday is a weekly data analysis and visualization challenge that provides a structured format to practice data wrangling and visualization skills using R programming language. Each week, a new dataset is posted to the TidyTuesday Github repository and participants are encouraged to explore and visualize the data using the principles of tidy data. [Continue reading](https://github.com/rbolt13/tidytuesday) ...

## [#Rsite](https://rbolt13.github.io/rsite/index.html)

Four different projects from Statistics 363: Introduction to R, which includes analysis of NYC Flight Data, investigating if Kobe Bryant had "hot hands", comparing Gas and Hydro power using base R and ggplot2, and exploring states with the highest and lowest numbers of Covid cases. [Continue reading](https://rbolt13.github.io/rsite/index.html) ...

## [Oregon Grown](https://rbolt13.github.io/Oregon-Grown/)

A state known for growing all varieties of trees and greenery, it’s no wonder that Oregon was one of the first states to legalize recreational cannabis in 2014. Measure 91 changed the lives of both those affiliated with cannabis and those who benefit from the tax revenue it brings in. While many businesses and industries struggled in 2020 due to COVID-19 the cannabis industry kept growing. [Continue reading](https://rbolt13.github.io/Oregon-Grown/) ...
