---
title: "Educational Insights"
toc: true
---

# Statistics

## STAT 464: Applied Regression Analysis 

Notes from Ge Shao’s **Applied Regression Analysis** Fall 2021 class. Topics include simple linear regression, least-square estimates, hypothesis testing, t-stat, p-stat, sum of squares estimates, mean square error, confidence interval, R squared, multiple linear models, hat matrix, multilinearity, model adequacy checking, residual analysis, PRESS statistic, detecting outliers, correcting model inadequacies, stabilizing variance, DIFFTS, DFBETAS, COVRATIO,... [Continue reading](https://rbolt13.github.io/stat464/).

## STAT 462: Introduction to Mathematical Statistics II

Notes from Nadee Jayasena's **Introduction ot Mathematical Statistics II** Winter 2022 class. Topics include marginal PDF's, joint PDF's and CDF's, independence of random variables, bivariate probability, conditional distribution, conditional covariance, correlation, univariate transformations, bivariate transformations, Jacobians, method of moment-generating functions, sampling distributions, central limit theorem, ... [Continue reading](https://rbolt13.github.io/stat462/)

## STAT 461: Introduction to Mathematical Statistics I

Notes from Dorcas Ofori-Boaten's **Introduction to Mathematical Statistics I** Fall 2021 class. Topics include mean, median, mode, variance, standard deviation, Empirical Rule, set theory, DeMorgans Law, Distributive Law, counting rules, statistical independence, mutual independence, total law of probability, Bayes Rule, discrete and continuous random variables, probability distribution, expected value, CDF, PMF, PDF, ... [Continue reading](https://rbolt13.github.io/stat461/)

## STAT 451: Applied Statistics for Engineers and Scientists

Notes from Subash Kochar's **Applied Statistics for Engineers and Scientists** Summer 2021 class. Topics include discrete and continous random various, bernoulli random variables, pmf, pdf, expeced value, variance, mean, standard deviation, probablity distributions: Poisson, binomial, uniform, normal, exponential, gamma, chi-squared, Weibull, lognormal, ...[Continue reading](https://rbolt13.github.io/stat451/)

# Mathematics

## MTH 388: Modern College Geometry

Notes from Rebecca Tramel's **Modern College Geometry** Winter 2022 class. Topics include axioms, proof writing, Euclid's Elements, congruence, isometries, triangles, area proofs, circles, group theory for symmetries, Euclidean distance, taxi-cab geometry, spherical geometry, hyperbolic geometry, ... [Continue reading](https://rbolt13.github.io/mth338/)

## MTH 344: Introduction to Group Theory 

Notes from Julie Bracken's **Introduction to Group Theory** Winter 2022 class. Topics include set theory, cancellation law, subgroups, cyclic subgroups, injecteive, surjective, bijective, function composition, permutation groups, symmetric groups, dihedral group, cycle decomposition, parity of transposistions, alternating groups, isomorphism, partitions, Lagrange's Theorem, homomorphism, normal subgroups, kernal, ... [Continue reading](https://rbolt13.github.io/mth344/)
