---
title: "Talks"
---

# [Code to Content](https://github.com/rbolt13/2024-PDX_RUG-Code_to_Content) (2024)

* Used 4 years of hands-on experience creating technical blogs to compile a short 6 minute presentation to guide and encourage R users to create and share their expertise and journeys online.  

* Created accessible slides with Quarto, and hosted on Github. 

* Presented as a [lightning talk at PDX R User Group](https://www.meetup.com/login/?returnUri=https%3A%2F%2Fwww.meetup.com%2Fportland-r-user-group%2Fevents%2F298359537%2F), February 2024. 

* Accepted as a presenter for a lightning talk at [Cascadia R Conference](https://cascadiarconf.com/), June 2024. 

# [Oregon Grown](https://github.com/rbolt13/Oregon-Grown) (2021)

* Used spatial references from Oregon Spatial Library, ARLIS, and PCC Geography Department to apply mapping techniques such as select by attribute, spatial join, clip, and XY Table to Point to investigate dispensary diversity in Oregon November 2020. 

* Formatted, organized, added classifications, and geocoded a data table of approximately 700 rows of data from the Oregon Liquor Control Commission’s active marijuanna retail license. 

* Discovered more than half of dispensaries in Oregon are owned by chains, and about 10% of dispensaries in Portland’s Urban Growth Boundary are owned by one chain, Groundworks. 

* Created an abstract that was accepted for [GIS in Action 2021](https://gisinaction2021.sched.com/directory/speakers), and presented virtually April 2021. 
