project:
  type: website

website:
  title: "Randi Bolt"
  favicon: img/2024-rbolt.png
  google-analytics: "G-GPSGHZ166H"
  page-navigation: true
  page-footer:
    right: "Made with [Quarto](https://quarto.org/) and deployed with [Netlify](https://www.netlify.com/)."
    center: "Randi Bolt 2024"
    left: 
      - icon: github
        href: links/github.qmd
      - icon: linkedin
        href: links/linkedin.qmd
      - icon: envelope
        href: mailto:randibolt93@gmail.com

  navbar:
    right:
      - text: "Blogs"
        menu:
          - icon: book
            text: Book Reviews
            href: blog/Book-Reviews/blog.qmd
          - icon: person
            text: Personal Blog
            href: blog/Personal-Blog/blog.qmd
          - icon: code
            text: Archive Blogs
            href: blog/Technical-Blog/blog.qmd
      - text: "Projects"
        menu:
          - icon: bar-chart-steps
            text: Dashboards
            href: projects/Dashboards.qmd
          - icon: bar-chart
            text: Data Visuals and Analysis
            href: projects/Data-Visuals-and-Analysis.qmd
          - icon: journal
            text: Educational Insights
            href: projects/Educational-Insights.qmd
          - icon: megaphone
            text: Talks
            href: projects/Talks.qmd
          - icon: laptop
            text: Technical Blogs
            href: projects/Technical-Blogs.qmd
      - text: "Links"
        menu:
          - icon: envelope
            text: Email
            href: mailto:randibolt93@gmail.com 
          - icon: github
            text: Github
            href: links/github.qmd
          - icon: linkedin
            text: Linkedin
            href: links/linkedin.qmd
          - icon: film
            text: Letterboxd
            href: links/letterboxd.qmd
          - icon: spotify
            text: Spotify
            href: links/spotify.qmd

      
format:
  html:
    theme: styles.scss
    template-partials:
      - metadata.html
      
comments: 
  giscus:
    repo: rbolt13/2024-rbolt.me