---
title: "Crafts - Baby Burp Rags"
date: "2024-05-01"
categories: ["Crafts", "Sewing"]
toc: true
draft: true
---

Craft a touching, homemade gift for an expecting parent with this guide to creating adorable baby burp rags. Create something unique and practical for their little ones. 

# Introduction 

Welcome to a heartwarming journey of crafting, where the simplest gifts are often the most cherished. In this post I describe the materials and steps needed to make a baby burp rag. Essential for keeping shoulders clean during burp time, these rags are far more that just practical items; they're tokens of love, sewn with care and thoughtfulness. A dear friend of mine taught me how to make these rags, that she received as gifts for her son over two decades ago. Since then, she has continued the tradition of crafting and gifting these rags, passing on this tradition to her friends. 

The inspiration for this particular tutorials comes from a very special place. As my little sister anticipates the arrival of her first child, I wanted to create something unique for her. Join me as I step through this project, creating not just burp rags, but lasting memories. 

# Materials Needed 

These are the materials you need 

* Iron: This is very important. Get comfortable using your iron, that is probably about 50% of this project. 

* 1 pack of 10 cloth diapers:  Some cloths diapers have an extra absorbent center. You might like this if you want your burp rags to have more pillow-y volume. For a baby to rest upon when its rested over the shoulder of the parent.  You might prefer against this if you want flatter more raggier burp rags. Specifically used for cleaning up messes. 

* Fabric scissors: These are not the same a regular scissors. 

* White thread: This is for the under side thread that will match the color or the diaper. 

* Various colored threads: This is for the accent stitches, and trim on the bottom. 

* 10 Different pieces of fabrics slightly larger than a diaper. 

* 10 pieces of trim a couple inches longer than the diaper. 

**Optional**

* Ribbons

# Preperation

* Iron all ten diapers, keeping extra attention to the edges where you will be sewing the fabric. 

* Iron diapers, fabric, and trim. 


# Instructions 


# Finishing Touches 

