---
title: "Week 27 Tidy Tuesday: Tidy Tuesday Meta Data"
date: "2024-07-02"
categories: ["#TidyTuesday", "R", "Data Visuals"]
draft: true
execute: 
  eval: false
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    code-tools: true
---

This... 


# 


```{r}
# Load packages -----------------------------------------------------------
library(tidyverse)
library(showtext)
library(ggtext)

# Load data ---------------------------------------------------------------
tt_datasets <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-02/tt_datasets.csv')
tt_summary <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-02/tt_summary.csv')
tt_urls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-02/tt_urls.csv')
tt_variables <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-02/tt_variables.csv')
```

```{r}
# Load fonts --------------------------------------------------------------
font_add_google("Yanone Kaffeesatz", "yanone")
showtext_auto()


# Define colours and fonts-------------------------------------------------
bg_col <- "grey98"
text_col <- "grey5"
highlight_col <- "#562457"
title_font <- "yanone"

# Define text -------------------------------------------------------------

title <- "Tidy Tuesday Observations"
st <- "subtitle goes here.... "
cap <- "**Data**: ttmeta package| **Graphic**: R. Bolt"
```


```{r}
# Data wrangling ----------------------------------------------------------
plot_data <- tt_datasets %>%
  group_by(year) %>%
  summarize(
    total_observations = sum(observations),
    total_variables = sum(variables)
  ) %>%
  mutate(
    stand_obs = (total_observations - mean(total_observations)) / sd(total_observations),
    stand_var = (total_variables - mean(total_variables)) / sd(total_variables)
  )

plot_data
```

```{r}
# Plot --------------------------------------------------------------------
# Create the line chart for standardized observations and variables
ggplot(plot_data, aes(x = year)) +
  geom_line(aes(y = stand_obs, color = "Standardized Observations"), size = 1) +
  geom_line(aes(y = stand_var, color = "Standardized Variables"), size = 1) +
  labs(title = "Trend of Standardized Observations and Variables per Dataset Over the Years",
       x = "Year",
       y = "Standardized Value",
       color = "Metric") +
  theme_minimal() +
  scale_color_manual(values = c("Standardized Observations" = "blue", "Standardized Variables" = "red"))


```


